### ISSUE TITLE
application crashes on start.

### ISSUE THREAD

**Issue by slycooper724** [imagitama/spotify-to-soundpad#1]
Starting up...
Connecting to Soundpad...
Error: connect ENOENT \\.\pipe\sp_remote_control
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\sp_remote_control'
}

**Comment by imagitama** [comment]
Is Soundpad and Spotify both open before you launch the app?

**Comment by slycooper724** [comment]
> Is Soundpad and Spotify both open before you launch the app?
Yes, both are open, but it still throws the error.

**Comment by imagitama** [comment]
What version of Windows, Spotify and Soundpad are you using?

**Comment by imagitama** [comment]
Closing as there is now an interface to help you out. If it still happens please comment and I'll re-open. https://github.com/imagitama/spotify-to-soundpad/releases/tag/1.0.0
