### ISSUE TITLE
application closes upon opening

### ISSUE THREAD

**Issue by yourprettygirl** [imagitama/spotify-to-soundpad#2]
whenever i double click and open the application it'll open then close, i can get it to stay open by clicking on it fast enough before it closes (lol, its also completely blank) but if i type anything it'll close. :( I've used this before and it worked flawlessly but now that i've reset my pc it refuses to workkkk.

**Comment by imagitama** [comment]
The software will crash if you do not have Spotify AND Soundpad open before you open it

**Comment by yourprettygirl** [comment]
yeah i did have soundpad and spotify open

**Comment by imagitama** [comment]
Added a new interface which should tell you what the app is actually doing: https://github.com/imagitama/spotify-to-soundpad/releases/tag/1.0.0
